apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-0-1-2
  labels:
    app: bff
    version: 0.1.2
spec:
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: bff
      version: 0.1.2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
      labels:
        app: bff
        version: 0.1.2
    spec:
      containers:
      - name: bff
        image: vampio/vamp-bizdata-demo-bff:0.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        - name: http-metrics
          containerPort: 9496
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 128Mi
            memory: 128Mi
        livenessProbe:
          httpGet:
             path: /healthz
             port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
             path: /healthz
             port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
