apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
    version: 0.1.0  
spec:
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: bff
      version: 0.1.0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
      labels:
        app: bff
        version: 0.1.0
    spec:
      containers:
      - name: bff
        image: vampio/vamp-bizdata-demo-bff:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        - name: http-metrics
          containerPort: 9496
          protocol: TCP
        livenessProbe:
          httpGet:
             path: /healthz
             port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
             path: /healthz
             port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
