apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff
  name: bff
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: bff
  type: LoadBalancer
