apiVersion: v1
kind: Service
metadata:
  labels:
    app: appointment
  name: appointment
spec:
  ports:
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: appointment
  type: LoadBalancer
