version: 2.1

parameters:
  delete:
    type: boolean
    default: false
  version:
    type: string
    default: ""
  kubernetes_cluster:
    type: string
    default: dev-orbtest-gs
  kubernetes_namespace:
    type: string
    default: production

jobs:
  delete-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:ff:35:9e:79:90:62:3b:38:fa:80:54:d7:8d:85:6a"
      - checkout
      - run:
          name: Delete Deployment
          command: |
            version="<< pipeline.parameters.version >>"
            echo "deployment-${version//./-}.yaml"
            git rm "cci-test/deployment-${version//./-}.yaml"
            ls
            git config --global user.email "bot@circleci.com"
            echo "1"
            git config --global user.name $VAMP_CI_USER
            echo "2"
            git config --list
            echo "3"
            git commit -a -m "Deleted deployment v$version"
            echo "4"
            git diff
            echo "5"
            git push origin master
            echo "6"

workflows:
  version: 2
  delete:
    when: << pipeline.parameters.delete >>
    jobs:
      context: vamp-build-context
      - delete-deployment
