version: 2.1

parameters:
  delete:
    type: boolean
    default: false
  version:
    type: string
    default: ""
  service_name:
    type: string
    default: ""
  kubernetes_namespace:
    type: string
    default: production

jobs:
  delete-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:ff:35:9e:79:90:62:3b:38:fa:80:54:d7:8d:85:6a"
      - checkout
      - run:
          name: Delete Deployment
          command: |
            version="<< pipeline.parameters.version >>"
            service="<< pipeline.parameters.service_name >>"
            echo "Delete $service/deployment-${version//./-}.yaml"
            git rm "$service/deployment-${version//./-}.yaml"
            git config --global user.email "bot@circleci.com"
            git config --global user.name $VAMP_CI_USER
            git commit -a -m "Deleted deployment v$version"
            git push origin main
  no-op:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Nothing to do
          command: |
            echo "Nothing to do (other than keep the build green)"


workflows:
  version: 2
  delete:
    when: << pipeline.parameters.delete >>
    jobs:
      - delete-deployment:
          context: vamp-build-context
  noop:
    when:
      not: << pipeline.parameters.delete >>
    jobs:
      - no-op
