apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-balanced
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-claim
spec:
  storageClassName: balanced
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
