apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-management
  name: user-management
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 5051
    protocol: TCP
    targetPort: 5051
  selector:
    app: user-management
  type: ClusterIP
